#!/bin/bash

declare -i goodPassCount=0

while read line; do
    min="$(echo $line | cut --fields=1 --delimiter="-")"
    max="$(echo $line | cut --fields=2 --delimiter="-" | cut --fields=1 --delimiter=" ")"
    letter="$(echo $line | cut --fields=2 --delimiter=" " | cut --fields=1 --delimiter=":")"
    password="$(echo $line | cut --fields=3 --delimiter=" ")"

    numOccur="$(echo "$password" | grep --only-matching "$letter" | wc --lines)"

    if test $numOccur -le $max -a $numOccur -ge $min; then
        ((++goodPassCount))
    fi
done < input

echo "result is $goodPassCount"